<?php

namespace App\Services\Nginx;

use App\Models\Site;

abstract class BaseNginxConfigGenerator
{
    /**
     * Generate the server block content for this project type.
     */
    abstract protected function generateServerBlock(Site $site): string;

    /**
     * Generate the complete Nginx configuration.
     */
    public function generate(Site $site, bool $ssl = false): string
    {
        $domain = $site->domain;
        $serverNames = $this->buildServerNames($site);
        $serverBlock = $this->generateServerBlock($site);
        $appName = config('app.name');

        return $this->wrapServerBlock($domain, $serverNames, $serverBlock, $ssl, $appName);
    }

    /**
     * Build the server_name list including nip.io domain for testing.
     */
    protected function buildServerNames(Site $site): string
    {
        $server = $site->server;
        $aliases = $site->aliases ?: [];
        $names = collect([$site->domain, ...$aliases]);

        // Add nip.io domain if server has an IP address
        if ($server && $server->ip_address) {
            $nipIoDomain = $this->generateNipIoDomain($site->domain, $server->ip_address);
            $names->push($nipIoDomain);
        }

        return $names->unique()->implode(' ');
    }

    /**
     * Generate a nip.io domain for testing purposes.
     */
    protected function generateNipIoDomain(string $domain, string $ipAddress): string
    {
        // Extract a clean subdomain from the domain (remove TLD and dots)
        // Example: "myapp.com" -> "myapp", "app.example.com" -> "app"
        $parts = explode('.', $domain);
        $subdomain = $parts[0];

        // Sanitize subdomain (remove invalid characters, keep alphanumeric and hyphens)
        $subdomain = preg_replace('/[^a-z0-9-]/i', '', $subdomain);

        // If subdomain is empty or too short, use a default
        if (empty($subdomain) || strlen($subdomain) < 2) {
            $subdomain = 'site';
        }

        return "{$subdomain}-{$ipAddress}.nip.io";
    }

    /**
     * Wrap server block content with HTTP/HTTPS listeners and SSL configuration.
     */
    protected function wrapServerBlock(string $domain, string $serverNames, string $serverBlock, bool $ssl, string $appName): string
    {
        if (! $ssl) {
            return <<<NGINX
# Nginx configuration for {$domain}
# Generated by {$appName}

server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};

{$serverBlock}
}
NGINX;
        }

        return <<<NGINX
# Nginx configuration for {$domain} (SSL)
# Generated by {$appName}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {$serverNames};

    ssl_certificate /etc/nginx/ssl/{$domain}/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/{$domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    add_header Strict-Transport-Security "max-age=63072000" always;

{$serverBlock}
}
NGINX;
    }

    /**
     * Get common security headers.
     */
    protected function getSecurityHeaders(): string
    {
        return <<<'NGINX'
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
NGINX;
    }

    /**
     * Get common PHP-FPM configuration.
     */
    protected function getPhpFpmConfig(string $phpVersion): string
    {
        return <<<NGINX
    # PHP-FPM configuration
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
NGINX;
    }

    /**
     * Get common hidden files protection.
     */
    protected function getHiddenFilesProtection(): string
    {
        return <<<'NGINX'
    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
NGINX;
    }

    /**
     * Get common favicon and robots.txt handling.
     */
    protected function getCommonLocations(): string
    {
        return <<<'NGINX'
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
NGINX;
    }
}
