<?php

namespace App\Services;

use App\Models\Site;

class NginxConfigService
{
    /**
     * Generate the Nginx configuration for a site.
     */
    public function generate(Site $site): string
    {
        $domain = $site->domain;
        $webRoot = $site->webRoot();
        $phpVersion = $site->php_version ?: '8.3';
        $aliases = $site->aliases ?: [];

        $serverNames = collect([$domain, ...$aliases])->implode(' ');

        return <<<NGINX
# Nginx configuration for {$domain}
# Generated by ServerForge

server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};

    root {$webRoot};

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    index index.php index.html index.htm;

    charset utf-8;

    # Handle static files
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # PHP-FPM configuration
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
NGINX;
    }

    /**
     * Generate SSL-enabled Nginx configuration.
     */
    public function generateWithSsl(Site $site): string
    {
        $domain = $site->domain;
        $webRoot = $site->webRoot();
        $phpVersion = $site->php_version ?: '8.3';
        $aliases = $site->aliases ?: [];

        $serverNames = collect([$domain, ...$aliases])->implode(' ');

        return <<<NGINX
# Nginx configuration for {$domain} (SSL)
# Generated by ServerForge

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {$serverNames};

    root {$webRoot};

    ssl_certificate /etc/nginx/ssl/{$domain}/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/{$domain}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    add_header Strict-Transport-Security "max-age=63072000" always;

    index index.php index.html index.htm;

    charset utf-8;

    # Handle static files
    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    # PHP-FPM configuration
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
NGINX;
    }

    /**
     * Get the path where the Nginx config should be stored on the server.
     */
    public function configPath(Site $site): string
    {
        return "/etc/nginx/sites-available/{$site->domain}";
    }

    /**
     * Get the path for the symlink in sites-enabled.
     */
    public function enabledPath(Site $site): string
    {
        return "/etc/nginx/sites-enabled/{$site->domain}";
    }
}
