<?php

namespace App\Services\Nginx\ConfigGenerators;

use App\Enums\WwwRedirect;
use App\Models\Site;
use App\Models\SiteDomain;

abstract class BaseNginxConfigGenerator
{
    /**
     * Generate the server block content for this project type.
     */
    abstract protected function generateServerBlock(Site $site): string;

    /**
     * Generate the complete Nginx configuration for a single site domain (one file per domain).
     */
    public function generateForSiteDomain(Site $site, SiteDomain $domain, bool $ssl = false): string
    {
        $serverNames = $this->buildServerNamesForDomain($domain);
        $serverBlock = $this->generateServerBlock($site);
        $appName = config('app.name');
        $preamble = $this->buildWwwRedirectPreamble($domain, $ssl);

        return $preamble.$this->wrapServerBlock($site, $domain, $serverNames, $serverBlock, $ssl, $appName);
    }

    /**
     * Forge-style ID-based cert paths. The same layout is used for the
     * wildcard-distributed cert (free-domain sites) and any future per-site
     * Let's Encrypt cert (custom domains) — the generator never has to branch
     * on the cert's origin.
     *
     * @return array{certificate: string, private_key: string}
     */
    protected function certificatePathsFor(Site $site, SiteDomain $domain): array
    {
        $base = "/etc/nginx/ssl/domains/{$site->id}/{$domain->id}";

        return [
            'certificate' => "{$base}/server.crt",
            'private_key' => "{$base}/server.key",
        ];
    }

    /**
     * Optional HTTP redirect blocks for www handling (apex hostnames only).
     */
    protected function buildWwwRedirectPreamble(SiteDomain $domain, bool $ssl): string
    {
        if ($ssl || ! $this->isApexHostname($domain->hostname)) {
            return '';
        }

        $host = $domain->hostname;
        $www = $domain->www_redirect;

        if ($www === WwwRedirect::FromWww) {
            $wwwHost = 'www.'.$host;

            return <<<NGINX
# Redirect www to apex
server {
    listen 80;
    listen [::]:80;
    server_name {$wwwHost};
    return 301 http://{$host}\$request_uri;
}


NGINX;
        }

        if ($www === WwwRedirect::ToWww) {
            $wwwHost = 'www.'.$host;

            return <<<NGINX
# Redirect apex to www
server {
    listen 80;
    listen [::]:80;
    server_name {$host};
    return 301 http://{$wwwHost}\$request_uri;
}


NGINX;
        }

        return '';
    }

    /**
     * Build server_name for a single domain row (one config file).
     */
    protected function buildServerNamesForDomain(SiteDomain $domain): string
    {
        $host = $domain->hostname;

        if ($domain->www_redirect === WwwRedirect::ToWww && $this->isApexHostname($host)) {
            return 'www.'.$host;
        }

        $names = [$host];

        if ($domain->wildcard_enabled && $this->isApexHostname($host)) {
            $names[] = '*.'.$host;
        }

        return collect($names)->unique()->implode(' ');
    }

    protected function isApexHostname(string $hostname): bool
    {
        return ! str_starts_with(strtolower($hostname), 'www.');
    }

    /**
     * Wrap server block content with HTTP/HTTPS listeners and SSL configuration.
     */
    protected function wrapServerBlock(Site $site, SiteDomain $siteDomain, string $serverNames, string $serverBlock, bool $ssl, string $appName): string
    {
        $hostname = $siteDomain->hostname;

        if (! $ssl) {
            return <<<NGINX
# Nginx configuration for {$hostname}
# Generated by {$appName}

server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};

{$serverBlock}
}
NGINX;
        }

        $certPaths = $this->certificatePathsFor($site, $siteDomain);

        return <<<NGINX
# Nginx configuration for {$hostname} (SSL)
# Generated by {$appName}

# Redirect HTTP to HTTPS
server {
    listen 80;
    listen [::]:80;
    server_name {$serverNames};
    return 301 https://\$host\$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {$serverNames};

    ssl_certificate {$certPaths['certificate']};
    ssl_certificate_key {$certPaths['private_key']};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;

    add_header Strict-Transport-Security "max-age=63072000" always;

{$serverBlock}
}
NGINX;
    }

    /**
     * Get common security headers.
     */
    protected function getSecurityHeaders(): string
    {
        return <<<'NGINX'
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
NGINX;
    }

    /**
     * Get common PHP-FPM configuration.
     */
    protected function getPhpFpmConfig(string $phpVersion): string
    {
        return <<<NGINX
    # PHP-FPM configuration
    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php{$phpVersion}-fpm.sock;
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }
NGINX;
    }

    /**
     * Get common hidden files protection.
     */
    protected function getHiddenFilesProtection(): string
    {
        return <<<'NGINX'
    # Deny access to hidden files
    location ~ /\.(?!well-known).* {
        deny all;
    }
NGINX;
    }

    /**
     * Get common favicon and robots.txt handling.
     */
    protected function getCommonLocations(): string
    {
        return <<<'NGINX'
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
NGINX;
    }
}
